apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: hospital-system
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "root123"
  MYSQL_PASSWORD: "hospital_pass"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: hospital-system
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "hospital_pass"
  JWT_SECRET: "your-super-secret-jwt-key-change-this-in-production-minimum-256-bits"
