# Application Configuration
spring.application.name=hospital-management-system
server.port=8080

# Active Profile
spring.profiles.active=dev

# API Base Path
# server.servlet.context-path=/api

# Jackson Configuration
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=UTC
